language: php

php:
  - '7.4snapshot'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'

git:
  quiet: true
  depth: 5

notifications:
  email: false

addons:
  apt:
    packages:
      - valgrind
      - gdb
      - lcov

env:
  global:
    - MAKEJOBS="-j$(getconf _NPROCESSORS_ONLN)"
    - COVERAGE=ON
    - ZEND_DONT_UNLOAD_MODULES=1
    - USE_ZEND_ALLOC=0
    - TRAVIS_COMMIT_LOG=`git log --format=fuller -2`
  matrix:
    - RE2C_VERSION="0.13.6"
    - RE2C_VERSION="1.1.1"

matrix:
  fast_finish: true

cache:
  apt: true
  timeout: 604800
  directories:
    - $HOME/.local/opt
    - $HOME/.cache/re2c

before_install:
  - phpenv config-rm xdebug.ini || true
  - ulimit -c unlimited -S || true

install:
  - .ci/install-re2c.sh
  - phpize
  - |
    ./configure \
      --with-php-config=$(phpenv which php-config) \
      --enable-zephir-parser \
      --enable-zephir-parser-debug \
      --enable-coverage
  - make $MAKEJOBS

before_script:
  - if [ $COVERAGE = "ON" ]; then make coverage-initial; fi
  - |
    if [ "$(php-config --vernum)" -ge "70300" ]; then
      echo "Patching PHP tests ruunner"

      # TODO: Move to makefile
      search_str="valgrind -q --tool=memcheck --trace-children=yes"
      add_str="--suppressions=./tests/php-7.3.supp"
      sed -e "s|'\($search_str\)'|'\1 $add_str'|" run-tests.php > tmp.php
      mv tmp.php run-tests.php
    fi

script:
  - make test NO_INTERACTION=1 REPORT_EXIT_STATUS=1 TEST_PHP_ARGS=-m

after_failure:
  - .ci/after-failure.sh

after_success:
  - |
      if [ $COVERAGE = "ON" ]; then
        make coverage-capture
        bash <(curl -s https://codecov.io/bash)
      fi

after_script:
  - printf "$TRAVIS_COMMIT_RANGE\n"
  - printf "$TRAVIS_COMMIT_LOG\n"
